# audit-service values
namespace: docvault

image:
  repository: duyimew/audit-service
  tag: "v81"
  digest: "sha256:4f01cf5193c45c7d20ab1cabf3aed7d9bfbfbdc93f07940b729807dd5443e9a6"

service:
  type: NodePort
  port: 3004
  nodePort: 30004
env:
  NODE_ENV: production
  PORT: "3004"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"

envFrom:
  - secretRef:
      name: docvault-app-secrets
