# audit-service values
namespace: docvault

image:
  repository: daithang59/audit-service
  tag: "v81"
  digest: ""

healthPath: /health

service:
  type: NodePort
  port: 3004
  nodePort: 30004
env:
  NODE_ENV: production
  PORT: "3004"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "docvault"
  KEYCLOAK_AUDIENCE: "docvault-gateway"

envFrom:
  - secretRef:
      name: docvault-app-secrets
