# document-service values
namespace: default

image:
  repository: duyimew/document-service
  tag: "v81"
  digest: "sha256:0b617cc97c3034058f3648f7b60d6bde3a6ffc7c639b51fd363c76a710ed9f56"

service:
  type: NodePort
  port: 3002
  nodePort: 30002
env:
  NODE_ENV: production
  PORT: "3002"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  METADATA_SERVICE_URL: "http://docvault-metadata:3001"
  AUDIT_SERVICE_URL: "http://docvault-audit-service:3004"
  S3_ENDPOINT: "http://minio:9000"
  S3_BUCKET: "docvault"
  S3_REGION: "us-east-1"
  S3_FORCE_PATH_STYLE: "true"

envFrom:
  - secretRef:
      name: docvault-app-secrets
