# gateway service values
namespace: default

image:
  repository: duyimew/gateway
  tag: "v81"
  digest: "sha256:92e814e05d7a9d0eb4885755ffc1217c635552a4e2463f7604e655cd19a7f589"

service:
  type: NodePort
  port: 3000
  nodePort: 30000
env:
  NODE_ENV: production
  PORT: "3000"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  METADATA_SERVICE_URL: "http://docvault-metadata:3001"
  DOCUMENTS_SERVICE_URL: "http://docvault-document-service:3002"
  WORKFLOW_SERVICE_URL: "http://docvault-workflow-service:3003"
  AUDIT_SERVICE_URL: "http://docvault-audit-service:3004"
  NOTIFY_SERVICE_URL: "http://docvault-notification-service:3005"

envFrom:
  - secretRef:
      name: docvault-app-secrets

probes:
  path: /api/health
