# gateway service values
namespace: docvault

image:
  repository: daithang59/gateway
  tag: "v81"
  digest: ""

healthPath: /api/health

service:
  type: ClusterIP
  port: 3000
env:
  NODE_ENV: production
  PORT: "3000"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "docvault"
  KEYCLOAK_AUDIENCE: "docvault-gateway"
  KEYCLOAK_CLIENT_ID: "docvault-gateway"
  GATEWAY_URL: "http://localhost:30000"
  FRONTEND_URL: "http://localhost:30006"
  ALLOWED_ORIGINS: "http://localhost:30006,http://localhost:3006"
  METADATA_SERVICE_URL: "http://docvault-metadata:3001"
  DOCUMENT_SERVICE_URL: "http://docvault-document-service:3002"
  WORKFLOW_SERVICE_URL: "http://docvault-workflow-service:3003"
  AUDIT_SERVICE_URL: "http://docvault-audit-service:3004"
  NOTIFICATION_SERVICE_URL: "http://docvault-notification-service:3005"

envFrom:
  - secretRef:
      name: docvault-app-secrets
