# metadata-service values
namespace: default

image:
  repository: daithang59/metadata-service
  tag: "v25"
  digest: "sha256:6caee1c586dd1e699344447990f0c7275498419feeaf8e083b4f130b67f8b5a2"

healthPath: /health

service:
  type: NodePort
  port: 3001
  nodePort: 30001
env:
  NODE_ENV: production
  PORT: "3001"
  KEYCLOAK_BASE_URL: "http://keycloak:18080"
  KEYCLOAK_REALM: "docvault"
  KEYCLOAK_AUDIENCE: "docvault-gateway"
  AUDIT_SERVICE_URL: "http://docvault-audit-service:3004"

envFrom:
  - secretRef:
      name: docvault-app-secrets
