# metadata-service values
namespace: docvault

image:
  repository: duyimew/metadata-service
  tag: "v81"
  digest: "sha256:e7f0bab48061a614ac7669fe965446bc56e3bcb096225ec9ff1584181a8d150c"

service:
  type: NodePort
  port: 3001
  nodePort: 30001
env:
  NODE_ENV: production
  PORT: "3001"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  AUDIT_SERVICE_URL: "http://docvault-audit-service:3004"

envFrom:
  - secretRef:
      name: docvault-app-secrets
