# notification-service values
image:
  repository: duyimew/notification-service
  tag: "v81"
  digest: "sha256:b3fea44f9bc6e272096e9fb8eba3644ef522e60a72f62ba1871db5f1d808ce92"

service:
  type: NodePort
  port: 3005
  nodePort: 30005
env:
  NODE_ENV: production
  PORT: "3005"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  AUDIT_SERVICE_URL: "http://docvault-audit-service:3004"

envFrom:
  - secretRef:
      name: docvault-app-secrets
