# web app values
namespace: default

image:
  repository: daithang59/docvault
  tag: "v25"
  digest: "sha256:e093e6dd1a98317d97a7d4b1c51d0e7f0173de887a7a8c5251e2318a589a92c8"

healthPath: /api/health

service:
  type: NodePort
  port: 3006
  nodePort: 30006
env:
  NODE_ENV: production
  PORT: "3006"
  NEXT_PUBLIC_APP_NAME: "DocVault"
  NEXT_PUBLIC_API_BASE_URL: "http://localhost:30000/api"
  GATEWAY_URL: "http://docvault-gateway:3000"
  FRONTEND_URL: "http://localhost:3006"
  KEYCLOAK_BASE_URL: "http://keycloak:18080"
  KEYCLOAK_REALM: "docvault"
  KEYCLOAK_CLIENT_ID: "docvault-gateway"

envFrom:
  - secretRef:
      name: docvault-app-secrets
