# workflow-service values
image:
  repository: duyimew/workflow-service
  tag: "v81"
  digest: "sha256:c0abf8919a8e28cefffb19aa49ab38a92e6b04c21fbeaa7a36230743b2ce2fa5"

service:
  type: NodePort
  port: 3003
  nodePort: 30003
env:
  NODE_ENV: production
  PORT: "3003"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  METADATA_SERVICE_URL: "http://docvault-metadata:3001"
  AUDIT_SERVICE_URL: "http://docvault-audit-service:3004"

envFrom:
  - secretRef:
      name: docvault-app-secrets
