# workflow-service values
namespace: docvault

image:
  repository: daithang59/workflow-service
  tag: "v44"
  digest: "sha256:e96f0f7cd5e521bddbf3bf53abf8021216797b78c7c56a5810ba33fea16be672"

healthPath: /health

service:
  type: ClusterIP
  port: 3003
env:
  NODE_ENV: production
  PORT: "3003"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "docvault"
  KEYCLOAK_AUDIENCE: "docvault-gateway"
  METADATA_SERVICE_URL: "http://docvault-metadata:3001"
  AUDIT_SERVICE_URL: "http://docvault-audit-service:3004"
  NOTIFICATION_SERVICE_URL: "http://docvault-notification-service:3005"

envFrom:
  - secretRef:
      name: docvault-app-secrets
