# workflow-service values
namespace: docvault

image:
  repository: daithang59/workflow-service
  tag: "v33"
  digest: "sha256:e54ad10f7a66aa15e49ff21dce979d4906bf0c6891a8d3ec022ac01b993cc1ed"

healthPath: /health

service:
  type: ClusterIP
  port: 3003
env:
  NODE_ENV: production
  PORT: "3003"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "docvault"
  KEYCLOAK_AUDIENCE: "docvault-gateway"
  METADATA_SERVICE_URL: "http://docvault-metadata:3001"
  AUDIT_SERVICE_URL: "http://docvault-audit-service:3004"
  NOTIFICATION_SERVICE_URL: "http://docvault-notification-service:3005"

envFrom:
  - secretRef:
      name: docvault-app-secrets
