apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docvault-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/daithang59/docvault.git'
    targetRevision: gitops-testing
    path: infra/k8s/charts/docvault-service
    helm:
      valueFiles:
        - ../../values/gateway.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docvault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docvault-metadata
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/daithang59/docvault.git'
    targetRevision: gitops-testing
    path: infra/k8s/charts/docvault-service
    helm:
      valueFiles:
        - ../../values/metadata-service.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docvault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docvault-audit-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/daithang59/docvault.git'
    targetRevision: gitops-testing
    path: infra/k8s/charts/docvault-service
    helm:
      valueFiles:
        - ../../values/audit-service.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docvault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docvault-notification-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/daithang59/docvault.git'
    targetRevision: gitops-testing
    path: infra/k8s/charts/docvault-service
    helm:
      valueFiles:
        - ../../values/notification-service.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docvault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docvault-workflow-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/daithang59/docvault.git'
    targetRevision: gitops-testing
    path: infra/k8s/charts/docvault-service
    helm:
      valueFiles:
        - ../../values/workflow-service.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docvault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docvault-document-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/daithang59/docvault.git'
    targetRevision: gitops-testing
    path: infra/k8s/charts/docvault-service
    helm:
      valueFiles:
        - ../../values/document-service.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docvault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docvault-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/daithang59/docvault.git'
    targetRevision: gitops-testing
    path: infra/k8s/charts/docvault-service
    helm:
      valueFiles:
        - ../../values/web.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docvault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
