apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docvault-app-secrets
  namespace: docvault
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: docvault-app-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: /docvault/testing/app
