apiVersion: v1
kind: Secret
metadata:
  name: docvault-app-secrets
  namespace: docvault
type: Opaque
stringData:
  DATABASE_URL: "postgresql://docvault:docvaultpw@db:5432/docvault_metadata?schema=public"
  MONGODB_URI: "mongodb://root:rootpw@mongo:27017/docvault_audit?authSource=admin"
  # MinIO / S3
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadminpw"
  # Keycloak
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "adminpw"
