apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: rootpw
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: mongo
    component: mongodb
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      component: mongodb
  template:
    metadata:
      labels:
        app: mongo
        component: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: docvault-gp3
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
    component: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
