apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: docvault
type: Opaque
stringData:
  POSTGRES_USER: docvault
  POSTGRES_PASSWORD: docvaultpw
  POSTGRES_DB: docvault_metadata
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: docvault
data:
  init.sql: |
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

    -- docvault_audit database
    CREATE DATABASE docvault_audit;
    \connect docvault_audit
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

    -- docvault_metadata database
    \connect postgres
    CREATE DATABASE docvault_metadata;
    \connect docvault_metadata
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

    CREATE TABLE IF NOT EXISTS _bootstrap (
      id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
      created_at timestamptz NOT NULL DEFAULT now()
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: docvault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-tmp
              mountPath: /tmp
            - name: postgres-run
              mountPath: /var/run/postgresql
      volumes:
        - name: postgres-init
          configMap:
            name: postgres-init-sql
        - name: postgres-data
          emptyDir: {}
        - name: postgres-tmp
          emptyDir: {}
        - name: postgres-run
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: docvault
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
